In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print("From list:", arr1)

From list: [1 2 3 4 5]


In [ ]:
arr2 = np.arange(0, 10, 2)  # start, stop, step
print("Using arange:", arr2)

Using arange: [0 2 4 6 8]


In [ ]:
arr3 = np.linspace(0, 1, 5)  # start, stop, number of elements
print("Using linspace:", arr3)

Using linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
zeros = np.zeros(5)
print("Zeros:", zeros)

Zeros: [0. 0. 0. 0. 0.]


In [ ]:
ones = np.ones(5)
print("Ones:", ones)

Ones: [1. 1. 1. 1. 1.]


In [ ]:
full = np.full(5, 7)  # shape, fill_value
print("Full (all 7s):", full)

Full (all 7s): [7 7 7 7 7]


In [ ]:
# Method 7: Identity matrix
identity = np.eye(3)
print("Identity matrix:\n", identity)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Method 8: Random arrays
random_arr = np.random.rand(5)  # Uniform distribution [0, 1)
print("Random (uniform):", random_arr)

Random (uniform): [0.55576824 0.56226747 0.89032097 0.68764463 0.3422895 ]


In [ ]:
random_int = np.random.randint(1, 10, size=5)  # [low, high), size
print("Random integers:", random_int)

Random integers: [9 7 8 3 3]


In [ ]:
# Type inference and common types
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])
arr_mixed = np.array([1, 2.5, 3])

In [ ]:
print(f"Integer: {arr_int.dtype}")
print(f"Float: {arr_float.dtype}")
print(f"Mixed: {arr_mixed.dtype}  (promoted to float)\n")

Integer: int64
Float: float64
Mixed: float64  (promoted to float)



In [ ]:
# Specifying types
arr1 = np.array([1, 2, 3], dtype=np.float32)
arr2 = arr_int.astype(np.float64)  # Convert types


In [ ]:
print(f"Specified float32: {arr1.dtype}")
print(f"Converted to float64: {arr2.dtype}\n")


Specified float32: float32
Converted to float64: float64



In [ ]:
print("Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element")

Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element


In [ ]:
# 2D array (matrix)
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix):")
print(matrix_2d)
print(f"Shape: {matrix_2d.shape}")  # (rows, columns)
print(f"Dimensions: {matrix_2d.ndim}")  # Number of dimensions
print(f"Size: {matrix_2d.size}")  # Total number of elements
print(f"Data type: {matrix_2d.dtype}")  # Data type of elements

2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64


In [ ]:
# 3D array
matrix_3d = np.array([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
print("\n3D Array:")
print(matrix_3d)
print(f"Shape: {matrix_3d.shape}")  # (depth, rows, columns)


3D Array:
[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
Shape: (2, 2, 3)


In [ ]:
# Creating multi-dimensional arrays with specific shapes
zeros_2d = np.zeros((3, 4))  # 3 rows, 4 columns
print("\n2D zeros array:")
print(zeros_2d)


2D zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones_3d = np.ones((2, 3, 4))  # 2x3x4 array
print(ones_3d)
print(f"\n3D ones array shape: {ones_3d.shape}")

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

3D ones array shape: (2, 3, 4)


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array:")
print(arr)
print(f"\nShape: {arr.shape}")  # Dimensions of the array
print(f"Size: {arr.size}")  # Total number of elements
print(f"ndim: {arr.ndim}")  # Number of dimensions
print(f"dtype: {arr.dtype}")  # Data type
print(f"itemsize: {arr.itemsize} bytes")  # Size of each element
print(f"nbytes: {arr.nbytes} bytes")  # Total memory used
print(f"T (transpose):\n{arr.T}")  # Transpose of the array

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Size: 12
ndim: 2
dtype: int64
itemsize: 8 bytes
nbytes: 96 bytes
T (transpose):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# 1D indexing (same as Python lists)
print("Original array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements 1 to 3:", arr[1:4])  # Slicing: [start:stop:step]
print("Every other element:", arr[::2])

Original array: [10 20 30 40 50]
First element: 10
Last element: 50
Elements 1 to 3: [20 30 40]
Every other element: [10 30 50]


In [ ]:
# 2D indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(matrix)
print("Element at row 1, column 2:", matrix[1, 2])  # Row, Column
print("First row:", matrix[0, :])  # All columns of first row
print("Second column:", matrix[:, 1])  # All rows of second column
print("Submatrix (first 2 rows, first 2 columns):")
print(matrix[0:2, 0:2])


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Submatrix (first 2 rows, first 2 columns):
[[1 2]
 [4 5]]


In [ ]:
# Boolean indexing - powerful feature!
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n--- Boolean Indexing ---")
print("Original:", arr)
print("Elements greater than 5:", arr[arr > 5])
print("Even numbers:", arr[arr % 2 == 0])


--- Boolean Indexing ---
Original: [ 1  2  3  4  5  6  7  8  9 10]
Elements greater than 5: [ 6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Array a:", a)
print("Array b:", b)

Array a: [1 2 3 4]
Array b: [5 6 7 8]


In [ ]:
# Element-wise operations
print("\n--- Element-wise Operations ---")
print("Addition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)  # Element-wise, NOT matrix multiplication
print("Division (a / b):", a / b)
print("Square root:", np.sqrt(a))


--- Element-wise Operations ---
Addition (a + b): [ 6  8 10 12]
Subtraction (a - b): [-4 -4 -4 -4]
Multiplication (a * b): [ 5 12 21 32]
Division (a / b): [0.2        0.33333333 0.42857143 0.5       ]
Square root: [1.         1.41421356 1.73205081 2.        ]


In [ ]:
# Scalar operations (broadcasting)
print("\n--- Scalar Operations ---")
print("a + 10:", a + 10)
print("a * 2:", a * 2)
print("a ** 3:", a ** 3)


--- Scalar Operations ---
a + 10: [11 12 13 14]
a * 2: [2 4 6 8]
a ** 3: [ 1  8 27 64]


In [ ]:
# Comparison operations
print("\n--- Comparison Operations ---")
print("a > 2:", a > 2)
print("a == 3:", a == 3)
print("a <= 2:", a <= 2)



--- Comparison Operations ---
a > 2: [False False  True  True]
a == 3: [False False  True False]
a <= 2: [ True  True False False]


In [ ]:
arr = np.arange(12)
print("Original 1D array:", arr)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
reshaped = arr.reshape(3, 4)  # Must match total size (3*4=12)
print("\nReshaped to 3x4:")
print(reshaped)


Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Flatten - convert to 1D
flattened = reshaped.flatten()
print("\nFlattened:", flattened)


Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Reshape with -1 (auto-calculate dimension)
auto_reshape = arr.reshape(2, -1)  # -1 means "calculate automatically"
print("\nAuto reshape (2 rows, auto columns):")
print(auto_reshape)



Auto reshape (2 rows, auto columns):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# Transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal matrix:")
print(matrix)
print("Transposed:")
print(matrix.T)


Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("\n--- Concatenation ---")
print("Array a:\n", a)
print("Array b:\n", b)
print("Vertical concatenation (vstack):")
print(np.vstack((a, b)))
print("Horizontal concatenation (hstack):")
print(np.hstack((a, b)))
print("Using concatenate:")
print(np.concatenate((a, b), axis=0))  # axis=0 for vertical
print(np.concatenate((a, b), axis=1))  # axis=1 for horizontal


--- Concatenation ---
Array a:
 [[1 2]
 [3 4]]
Array b:
 [[5 6]
 [7 8]]
Vertical concatenation (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal concatenation (hstack):
[[1 2 5 6]
 [3 4 7 8]]
Using concatenate:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Understanding dimensions
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:")
print(f"  {arr_1d} → shape: {arr_1d.shape}, ndim: {arr_1d.ndim} (axis 0 only)\n")

print("2D Array:")
print(f"  {arr_2d}")
print(f"  shape: {arr_2d.shape} (rows, columns)")
print(f"  ndim: {arr_2d.ndim} (axis 0=rows, axis 1=columns)")

1D Array:
  [1 2 3 4 5] → shape: (5,), ndim: 1 (axis 0 only)

2D Array:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
  shape: (3, 3) (rows, columns)
  ndim: 2 (axis 0=rows, axis 1=columns)


In [ ]:
# Axis in operations: specifies which dimension to collapse
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}\n")

# axis=0: collapse rows (operate down columns) → one value per column
sum_axis0 = np.sum(matrix, axis=0)
print(f"axis=0 (down rows): {sum_axis0}  → shape: {sum_axis0.shape}")
print(f"  Example: Column 0 sum = {matrix[0,0]} + {matrix[1,0]} + {matrix[2,0]} = {sum_axis0[0]}\n")

# axis=1: collapse columns (operate across rows) → one value per row
sum_axis1 = np.sum(matrix, axis=1)
print(f"axis=1 (across columns): {sum_axis1}  → shape: {sum_axis1.shape}")
print(f"  Example: Row 0 sum = {matrix[0,0]} + {matrix[0,1]} + {matrix[0,2]} = {sum_axis1[0]}\n")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

axis=0 (down rows): [12 15 18]  → shape: (3,)
  Example: Column 0 sum = 1 + 4 + 7 = 12

axis=1 (across columns): [ 6 15 24]  → shape: (3,)
  Example: Row 0 sum = 1 + 2 + 3 = 6



In [ ]:
# 3D Arrays: Axis with more than 2 dimensions
# Think: (depth, rows, columns) or (samples, height, width)
arr_3d = np.array([
    [[1, 2, 3],    # First 2D slice (page 0)
     [4, 5, 6]],
    [[7, 8, 9],    # Second 2D slice (page 1)
     [10, 11, 12]]
])
print("3D Array (shape: 2x2x3):")
print("Think: 2 pages, each with a 2x3 matrix")
print(arr_3d)
print(f"Shape: {arr_3d.shape}  (depth=2, rows=2, columns=3)\n")

# axis=0: collapse depth (across pages) → result: 2D (2×3)
sum_axis0 = np.sum(arr_3d, axis=0)
print(f"axis=0 (across pages):\n{sum_axis0}  → shape: {sum_axis0.shape}")
print(f"  Example: [0,0,0] = {arr_3d[0,0,0]} + {arr_3d[1,0,0]} = {sum_axis0[0,0]}\n")

# axis=1: collapse rows (down each page) → result: 2D (2×3)
sum_axis1 = np.sum(arr_3d, axis=1)
print(f"axis=1 (down rows):\n{sum_axis1}  → shape: {sum_axis1.shape}")
print(f"  Example: [0,0] = {arr_3d[0,0,0]} + {arr_3d[0,1,0]} = {sum_axis1[0,0]}\n")

# axis=2: collapse columns (across each row) → result: 2D (2×2)
sum_axis2 = np.sum(arr_3d, axis=2)
print(f"axis=2 (across columns):\n{sum_axis2}  → shape: {sum_axis2.shape}")
print(f"  Example: [0,0] = {arr_3d[0,0,0]} + {arr_3d[0,0,1]} + {arr_3d[0,0,2]} = {sum_axis2[0,0]}\n")

3D Array (shape: 2x2x3):
Think: 2 pages, each with a 2x3 matrix
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)  (depth=2, rows=2, columns=3)

axis=0 (across pages):
[[ 8 10 12]
 [14 16 18]]  → shape: (2, 3)
  Example: [0,0,0] = 1 + 7 = 8

axis=1 (down rows):
[[ 5  7  9]
 [17 19 21]]  → shape: (2, 3)
  Example: [0,0] = 1 + 4 = 5

axis=2 (across columns):
[[ 6 15]
 [24 33]]  → shape: (2, 2)
  Example: [0,0] = 1 + 2 + 3 = 6



In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Array:", arr)

Array: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Basic statistics
print(f"\n--- Basic Statistics ---")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Index of min: {np.argmin(arr)}")
print(f"Index of max: {np.argmax(arr)}")



--- Basic Statistics ---
Sum: 55
Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Index of min: 0
Index of max: 9


In [ ]:
# 2D array statistics (with axis parameter)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n--- 2D Array Statistics ---")
print("Matrix:")
print(matrix)
print(f"Sum of all elements: {np.sum(matrix)}")
print(f"Sum along rows (axis=0): {np.sum(matrix, axis=0)}")  # Column sums
print(f"Sum along columns (axis=1): {np.sum(matrix, axis=1)}")  # Row sums
print(f"Mean of each column: {np.mean(matrix, axis=0)}")
print(f"Mean of each row: {np.mean(matrix, axis=1)}")


--- 2D Array Statistics ---
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Sum along rows (axis=0): [12 15 18]
Sum along columns (axis=1): [ 6 15 24]
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]


In [ ]:
# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix a:")
print(a)
print("\nMatrix b:")
print(b)


Matrix a:
[[1 2]
 [3 4]]

Matrix b:
[[5 6]
 [7 8]]


In [ ]:
# Element-wise multiplication (NOT matrix multiplication)
print("\nElement-wise multiplication (a * b):")
print(a * b)



Element-wise multiplication (a * b):
[[ 5 12]
 [21 32]]


In [ ]:
# Dot product of vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(f"\nDot product of vectors {v1} and {v2}: {np.dot(v1, v2)}")


Dot product of vectors [1 2 3] and [4 5 6]: 32


In [ ]:
# Matrix properties
matrix = np.array([[1, 2], [3, 4]])
print("\n--- Matrix Properties ---")
print("Matrix:")
print(matrix)
print(f"Determinant: {np.linalg.det(matrix)}")
print(f"Inverse:")
print(np.linalg.inv(matrix))
print(f"Transpose:")
print(matrix.T)


--- Matrix Properties ---
Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Transpose:
[[1 3]
 [2 4]]


In [ ]:
# Eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(matrix)
print(f"\nEigenvalues: {eigenvals}")
print(f"Eigenvectors:\n{eigenvecs}")


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print("Original array:", arr)

Original array: [3 1 4 1 5 9 2 6]


In [ ]:
# Sorting
print("\n--- Sorting ---")
print("Sorted array:", np.sort(arr))  # Returns sorted copy
print("Original unchanged:", arr)
arr.sort()  # In-place sort
print("After in-place sort:", arr)


--- Sorting ---
Sorted array: [1 1 2 3 4 5 6 9]
Original unchanged: [3 1 4 1 5 9 2 6]
After in-place sort: [1 1 2 3 4 5 6 9]


In [ ]:
# Unique elements
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
print("\n--- Unique Elements ---")
print("Array:", arr_with_duplicates)
print("Unique values:", np.unique(arr_with_duplicates))


--- Unique Elements ---
Array: [1 2 2 3 3 3 4]
Unique values: [1 2 3 4]


In [ ]:
# Searching
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n--- Searching ---")
print("Array:", arr)
print("Where is value > 5?", np.where(arr > 5))
print("Values where condition is True:", arr[np.where(arr > 5)])


--- Searching ---
Array: [ 1  2  3  4  5  6  7  8  9 10]
Where is value > 5? (array([5, 6, 7, 8, 9]),)
Values where condition is True: [ 6  7  8  9 10]


In [ ]:
# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\n--- Stacking ---")
print("Array a:", a)
print("Array b:", b)
print("Stack vertically:", np.vstack((a, b)))
print("Stack horizontally:", np.hstack((a, b)))
print("Stack as columns:", np.column_stack((a, b)))



--- Stacking ---
Array a: [1 2 3]
Array b: [4 5 6]
Stack vertically: [[1 2 3]
 [4 5 6]]
Stack horizontally: [1 2 3 4 5 6]
Stack as columns: [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Simulate a grayscale image (2D array) with values 0-255
# Let's create a simple 10x10 "image"
image = np.random.randint(0, 256, size=(10, 10))
print("Original 'image' (10x10 array):")
print(image)

Original 'image' (10x10 array):
[[202  39 172 249  76   5  31 223 226  55]
 [ 41  82 242  34  42  96 170 225 157 153]
 [150 247   1 105 131  42  90 225 131 133]
 [145 238 233 241 209 195 188 169 119  11]
 [219  21 134  11 146 143 253  65   6  26]
 [ 28  17 105 209 123 137  43  82 177  78]
 [181 165  42 142 169  55  22 124  43 129]
 [ 37   6 131 117  29  19 114  42  45 148]
 [148 255 165 133 167  97  41  32  20  27]
 [ 43  71 220  30 115 126   6  70 174 175]]


In [ ]:
# Image operations
print(f"\n--- Image Statistics ---")
print(f"Brightness (mean): {np.mean(image):.2f}")
print(f"Contrast (std): {np.std(image):.2f}")
print(f"Min pixel value: {np.min(image)}")
print(f"Max pixel value: {np.max(image)}")



--- Image Statistics ---
Brightness (mean): 114.21
Contrast (std): 74.88
Min pixel value: 1
Max pixel value: 255


In [ ]:
# Brightness adjustment (add constant)
brighter = np.clip(image + 50, 0, 255)  # Clip to valid range
print(f"\nBrightness increased (mean: {np.mean(brighter):.2f})")

# Contrast adjustment (multiply)
contrast = np.clip(image * 1.5, 0, 255)
print(f"Contrast increased (std: {np.std(contrast):.2f})")


Brightness increased (mean: 159.87)
Contrast increased (std: 89.86)


In [ ]:
# Simulate student test scores (3 tests, 5 students)
scores = np.array([
    [85, 90, 88],  # Student 1
    [92, 87, 91],  # Student 2
    [78, 82, 80],  # Student 3
    [95, 98, 96],  # Student 4
    [88, 85, 90]   # Student 5
])

print("Test Scores Matrix (5 students, 3 tests):")
print(scores)


Test Scores Matrix (5 students, 3 tests):
[[85 90 88]
 [92 87 91]
 [78 82 80]
 [95 98 96]
 [88 85 90]]


In [ ]:
# Calculate statistics
print("\n--- Student Statistics ---")
student_averages = np.mean(scores, axis=1)
print("Average score per student:", student_averages)
print("Best student average:", np.max(student_averages))
print("Student with best average (index):", np.argmax(student_averages))


--- Student Statistics ---
Average score per student: [87.66666667 90.         80.         96.33333333 87.66666667]
Best student average: 96.33333333333333
Student with best average (index): 3


In [ ]:
print("\n--- Test Statistics ---")
test_averages = np.mean(scores, axis=0)
print("Average score per test:", test_averages)
print("Hardest test (lowest average):", np.argmin(test_averages))
print("Easiest test (highest average):", np.argmax(test_averages))


--- Test Statistics ---
Average score per test: [87.6 88.4 89. ]
Hardest test (lowest average): 0
Easiest test (highest average): 2


In [ ]:
# Find students who scored above 90 in all tests
excellent_students = np.all(scores > 90, axis=1)
print("\n--- Excellent Students (all tests > 90) ---")
print("Boolean mask:", excellent_students)
print("Indices:", np.where(excellent_students)[0])
print("Scores of excellent students:")
print(scores[excellent_students])


--- Excellent Students (all tests > 90) ---
Boolean mask: [False False False  True False]
Indices: [3]
Scores of excellent students:
[[95 98 96]]
